# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    threshold: str
    actionExpiryDays: str
    councilMemberNameMaxLength: str
    councilMemberWebsiteMaxLength: str
    councilMemberImageMaxLength: str


class CouncilMembers(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    website: str
    image: str


class ActionsLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    initiator: str
    actionType: str
    executed: bool
    status: str
    signersCount: str
    dataMap: Dict[str, str]
    startDateTime: str
    startLevel: str
    executedDateTime: str | None
    executedLevel: str | None
    expirationDateTime: str


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str


class ActionsSigner(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Dict[str, Any]


class BreakGlassStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    glassBroken: bool
    councilMembers: Dict[str, CouncilMembers]
    councilSize: str
    actionsLedger: Dict[str, ActionsLedger]
    actionsSigners: List[ActionsSigner]
    actionCounter: str
    lambdaLedger: Dict[str, str]
