# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class CollateralItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: str
    tokenName: str


class Depositors(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    any: Dict[str, Any]


class Depositors1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    whitelist: List[str]


class CreateVaultParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baker: str | None = None
    loanTokenName: str
    name: str
    collateral: List[CollateralItem] | None = None
    depositors: Depositors | Depositors1
