# generated by datamodel-codegen:
#   filename:  createVault.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class CollateralItem(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    tokenName: str


class Depositors(BaseModel):
    class Config:
        extra = Extra.forbid

    any: Dict[str, Any]


class Depositors1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: List[str]


class CreateVaultParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    baker: str | None
    loanTokenName: str
    name: str
    collateral: List[CollateralItem] | None
    depositors: Depositors | Depositors1
