# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TargetEntrypoint(BaseModel):
    class Config:
        extra = Extra.forbid

    createVault: bool


class TargetEntrypoint1(BaseModel):
    class Config:
        extra = Extra.forbid

    empty: Dict[str, Any]


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: TargetEntrypoint | TargetEntrypoint1
    empty: Dict[str, Any]
