# generated by datamodel-codegen:
#   filename:  banSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BanSatelliteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteToBeBanned: str
    purpose: str
