# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Token(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenContractAddress: str
    tokenId: str


class Token1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Fa2


class Token2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mav: Dict[str, Any]


class TransferListItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to_: str
    amount: str
    token: Token | Token1 | Token2


class FixMistakenTransferParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetContractAddress: str
    purpose: str
    transferList: List[TransferListItem]
