# generated by datamodel-codegen:
#   filename:  removeOracleInAggregator.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RemoveOracleInAggregatorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    oracleAddress: str
    aggregatorAddress: str
    purpose: str
