# generated by datamodel-codegen:
#   filename:  removeAllSatelliteOracles.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RemoveAllSatelliteOraclesParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteAddress: str
    purpose: str
