# generated by datamodel-codegen:
#   filename:  restoreSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RestoreSatelliteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteToBeRestored: str
    purpose: str
