# generated by datamodel-codegen:
#   filename:  suspendSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SuspendSatelliteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteToBeSuspended: str
    purpose: str
