# generated by datamodel-codegen:
#   filename:  togglePauseAggregator.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class Status(BaseModel):
    class Config:
        extra = Extra.forbid

    pauseAll: Dict[str, Any]


class Status1(BaseModel):
    class Config:
        extra = Extra.forbid

    unpauseAll: Dict[str, Any]


class TogglePauseAggregatorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorAddress: str
    purpose: str
    status: Status | Status1
