# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class Status(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pauseAll: Dict[str, Any]


class Status1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unpauseAll: Dict[str, Any]


class TogglePauseAggregatorParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aggregatorAddress: str
    purpose: str
    status: Status | Status1
