# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configActionDurationInDays: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    configApprovalPercentage: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxActionsPerSatellite: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    class Config:
        extra = Extra.forbid

    configPurposeMaxLength: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
    )
