# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class UpdateConfigAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configActionDurationInDays: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configApprovalPercentage: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMaxActionsPerSatellite: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configPurposeMaxLength: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
    )
