# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class VesteeLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    totalAllocatedAmount: str
    claimAmountPerMonth: str
    startTimestamp: str
    vestingMonths: str
    cliffMonths: str
    endCliffDateTime: str
    endVestingDateTime: str
    status: str
    totalRemainder: str
    totalClaimed: str
    monthsClaimed: str
    monthsRemaining: str
    nextRedemptionTimestamp: str
    lastClaimedTimestamp: str


class VestingStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    vesteeLedger: Dict[str, VesteeLedger]
    totalVestedAmount: str
    lambdaLedger: Dict[str, str]
