# generated by datamodel-codegen:
#   filename:  addLiquidity.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class AddLiquidityParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    loanTokenName: str
    amount: str
