# generated by datamodel-codegen:
#   filename:  borrow.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BorrowParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultId: str
    quantity: str
