# generated by datamodel-codegen:
#   filename:  liquidateVault.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class LiquidateVaultParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultId: str
    vaultOwner: str
    amount: str
