# generated by datamodel-codegen:
#   filename:  markForLiquidation.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class MarkForLiquidationParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultId: str
    vaultOwner: str
