# generated by datamodel-codegen:
#   filename:  registerWithdrawal.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class Handle(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class RegisterWithdrawalParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    handle: Handle
    amount: str
    tokenName: str
