# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RegisterVaultCreationParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vaultOwner: str
    vaultId: str
    vaultAddress: str
    loanTokenName: str
