# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Handle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    owner: str


class RegisterDepositParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    handle: Handle
    amount: str
    tokenName: str
