# generated by datamodel-codegen:
#   filename:  registerVaultCreation.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RegisterVaultCreationParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultOwner: str
    vaultId: str
    vaultAddress: str
    loanTokenName: str
