# generated by datamodel-codegen:
#   filename:  repay.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RepayParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultId: str
    quantity: str
