# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class TokenType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenContractAddress: str
    tokenId: str


class TokenType1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Fa2


class TokenType2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mav: Dict[str, Any]


class CreateLoanToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenName: str
    tokenDecimals: str
    oracleAddress: str
    mTokenAddress: str
    reserveRatio: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    minRepaymentAmount: str
    tokenType: TokenType | TokenType1 | TokenType2


class Action(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createLoanToken: CreateLoanToken


class UpdateLoanToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenName: str
    oracleAddress: str
    reserveRatio: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    minRepaymentAmount: str
    isPaused: bool


class Action1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateLoanToken: UpdateLoanToken


class SetLoanTokenParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: Action | Action1
    empty: Dict[str, Any]
