# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class TokenType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenContractAddress: str
    tokenId: str


class TokenType1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Fa2


class TokenType2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mav: Dict[str, Any]


class CreateCollateralToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenName: str
    tokenContractAddress: str
    tokenDecimals: str
    oracleAddress: str
    protected: bool
    isScaledToken: bool
    isStakedToken: bool
    stakingContractAddress: str | None = None
    maxDepositAmount: str | None = None
    tokenType: TokenType | TokenType1 | TokenType2


class Action(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createCollateralToken: CreateCollateralToken


class UpdateCollateralToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenName: str
    oracleAddress: str
    isPaused: bool
    stakingContractAddress: str | None = None
    maxDepositAmount: str | None = None


class Action1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateCollateralToken: UpdateCollateralToken


class SetCollateralTokenParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: Action | Action1
    empty: Dict[str, Any]
