# generated by datamodel-codegen:
#   filename:  setCollateralToken.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TokenType(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenType1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenType2(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class CreateCollateralToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenContractAddress: str
    tokenDecimals: str
    oracleAddress: str
    protected: bool
    isScaledToken: bool
    isStakedToken: bool
    stakingContractAddress: str | None
    maxDepositAmount: str | None
    tokenType: TokenType | TokenType1 | TokenType2


class Action(BaseModel):
    class Config:
        extra = Extra.forbid

    createCollateralToken: CreateCollateralToken


class UpdateCollateralToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    oracleAddress: str
    isPaused: bool
    stakingContractAddress: str | None
    maxDepositAmount: str | None


class Action1(BaseModel):
    class Config:
        extra = Extra.forbid

    updateCollateralToken: UpdateCollateralToken


class SetCollateralTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    action: Action | Action1
    empty: Dict[str, Any]
