# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class TargetEntrypoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addLiquidity: bool


class TargetEntrypoint1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    borrow: bool


class TargetEntrypoint2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    closeVault: bool


class TargetEntrypoint3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    liquidateVault: bool


class TargetEntrypoint4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    markForLiquidation: bool


class TargetEntrypoint5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    registerDeposit: bool


class TargetEntrypoint6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    registerVaultCreation: bool


class TargetEntrypoint7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    registerWithdrawal: bool


class TargetEntrypoint8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    removeLiquidity: bool


class TargetEntrypoint9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    repay: bool


class TargetEntrypoint10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    setCollateralToken: bool


class TargetEntrypoint11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    setLoanToken: bool


class TargetEntrypoint12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vaultDeposit: bool


class TargetEntrypoint13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vaultDepositStakedToken: bool


class TargetEntrypoint14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vaultOnLiquidate: bool


class TargetEntrypoint15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vaultWithdraw: bool


class TargetEntrypoint16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vaultWithdrawStakedToken: bool


class TogglePauseEntrypointParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetEntrypoint: (
        TargetEntrypoint
        | TargetEntrypoint1
        | TargetEntrypoint2
        | TargetEntrypoint3
        | TargetEntrypoint4
        | TargetEntrypoint5
        | TargetEntrypoint6
        | TargetEntrypoint7
        | TargetEntrypoint8
        | TargetEntrypoint9
        | TargetEntrypoint10
        | TargetEntrypoint11
        | TargetEntrypoint12
        | TargetEntrypoint13
        | TargetEntrypoint14
        | TargetEntrypoint15
        | TargetEntrypoint16
    )
    empty: Dict[str, Any]
