# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class UpdateConfigAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configAdminLiquidationFee: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configCollateralRatio: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configInterestTreasuryShare: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configLastCompletedDataMaxDelay: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configLiquidationDelayInMins: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configLiquidationFeePercent: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configLiquidationMaxDuration: Dict[str, Any]


class UpdateConfigAction7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configLiquidationRatio: Dict[str, Any]


class UpdateConfigAction8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMaxVaultLiqPercent: Dict[str, Any]


class UpdateConfigAction9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinLoanFeeTreasuryShare: Dict[str, Any]


class UpdateConfigAction10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinimumLoanFeePercent: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
        | UpdateConfigAction7
        | UpdateConfigAction8
        | UpdateConfigAction9
        | UpdateConfigAction10
    )
