# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configAdminLiquidationFee: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    configCollateralRatio: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    class Config:
        extra = Extra.forbid

    configInterestTreasuryShare: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    class Config:
        extra = Extra.forbid

    configLastCompletedDataMaxDelay: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationDelayInMins: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationFeePercent: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationMaxDuration: Dict[str, Any]


class UpdateConfigAction7(BaseModel):
    class Config:
        extra = Extra.forbid

    configLiquidationRatio: Dict[str, Any]


class UpdateConfigAction8(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxVaultLiqPercent: Dict[str, Any]


class UpdateConfigAction9(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinLoanFeeTreasuryShare: Dict[str, Any]


class UpdateConfigAction10(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinimumLoanFeePercent: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
        | UpdateConfigAction7
        | UpdateConfigAction8
        | UpdateConfigAction9
        | UpdateConfigAction10
    )
