# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class VaultDepositStakedTokenParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenName: str
    vaultId: str
    depositAmount: str
