# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    minMvkAmount: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    stakeIsPaused: bool
    unstakeIsPaused: bool
    compoundIsPaused: bool
    farmClaimIsPaused: bool
    onVaultDepositStakeIsPaused: bool
    onVaultWithdrawStakeIsPaused: bool
    onVaultLiquidateStakeIsPaused: bool


class UserStakeBalanceLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    balance: str
    totalExitFeeRewardsClaimed: str
    totalSatelliteRewardsClaimed: str
    totalFarmRewardsClaimed: str
    participationFeesPerShare: str


class DoormanStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    userStakeBalanceLedger: Dict[str, UserStakeBalanceLedger]
    unclaimedRewards: str
    accumulatedFeesPerShare: str
    lambdaLedger: Dict[str, str]
