# generated by datamodel-codegen:
#   filename:  dropFinancialRequest.json

from __future__ import annotations

from pydantic import BaseModel


class DropFinancialRequestParameter(BaseModel):
    __root__: str
