# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RequestTokensParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    treasuryAddress: str
    receiverAddress: str
    tokenContractAddress: str
    tokenName: str
    tokenAmount: str
    tokenType: str
    tokenId: str
    purpose: str
