# generated by datamodel-codegen:
#   filename:  requestTokens.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RequestTokensParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    treasuryAddress: str
    receiverAddress: str
    tokenContractAddress: str
    tokenName: str
    tokenAmount: str
    tokenType: str
    tokenId: str
    purpose: str
