# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict, Field


class Vote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nay: Dict[str, Any]


class Vote1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pass_: Dict[str, Any] = Field(..., alias='pass')


class Vote2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    yay: Dict[str, Any]


class VoteForRequestParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: str
    vote: Vote | Vote1 | Vote2
