# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict


class OracleLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oraclePublicKey: str
    oraclePeerId: str


class AggregatorConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decimals: str
    alphaPercentPerThousand: str
    percentOracleThreshold: str
    heartbeatSeconds: str
    rewardAmountStakedMvn: str
    rewardAmountMvrk: str


class CreateAggregatorParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    addToGeneralContracts: bool
    oracleLedger: Dict[str, OracleLedger]
    aggregatorConfig: AggregatorConfig
    metadata: str
