# generated by datamodel-codegen:
#   filename:  createAggregator.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class OracleLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    oraclePublicKey: str
    oraclePeerId: str


class AggregatorConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    alphaPercentPerThousand: str
    percentOracleThreshold: str
    heartbeatSeconds: str
    rewardAmountStakedMvn: str
    rewardAmountMvrk: str


class CreateAggregatorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    addToGeneralContracts: bool
    oracleLedger: Dict[str, OracleLedger]
    aggregatorConfig: AggregatorConfig
    metadata: str
