# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class TargetEntrypoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createAggregator: bool


class TargetEntrypoint1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    distributeRewardMvrk: bool


class TargetEntrypoint2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    distributeRewardStakedMvn: bool


class TargetEntrypoint3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trackAggregator: bool


class TargetEntrypoint4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    untrackAggregator: bool


class TogglePauseEntrypointParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetEntrypoint: (
        TargetEntrypoint
        | TargetEntrypoint1
        | TargetEntrypoint2
        | TargetEntrypoint3
        | TargetEntrypoint4
    )
    empty: Dict[str, Any]
