# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TargetEntrypoint(BaseModel):
    class Config:
        extra = Extra.forbid

    createAggregator: bool


class TargetEntrypoint1(BaseModel):
    class Config:
        extra = Extra.forbid

    distributeRewardMvrk: bool


class TargetEntrypoint2(BaseModel):
    class Config:
        extra = Extra.forbid

    distributeRewardStakedMvn: bool


class TargetEntrypoint3(BaseModel):
    class Config:
        extra = Extra.forbid

    trackAggregator: bool


class TargetEntrypoint4(BaseModel):
    class Config:
        extra = Extra.forbid

    untrackAggregator: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: (
        TargetEntrypoint
        | TargetEntrypoint1
        | TargetEntrypoint2
        | TargetEntrypoint3
        | TargetEntrypoint4
    )
    empty: Dict[str, Any]
