# generated by datamodel-codegen:
#   filename:  trackAggregator.json

from __future__ import annotations

from pydantic import BaseModel


class TrackAggregatorParameter(BaseModel):
    __root__: str
