# generated by datamodel-codegen:
#   filename:  untrackAggregator.json

from __future__ import annotations

from pydantic import BaseModel


class UntrackAggregatorParameter(BaseModel):
    __root__: str
