# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class UpdateConfigAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configAggregatorNameMaxLength: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    empty: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateConfigNewValue: str
    updateConfigAction: UpdateConfigAction | UpdateConfigAction1
