# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CreateTreasuryParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baker: str | None = None
    name: str
    addToGeneralContracts: bool
    metadata: str
