# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TargetEntrypoint(BaseModel):
    class Config:
        extra = Extra.forbid

    createTreasury: bool


class TargetEntrypoint1(BaseModel):
    class Config:
        extra = Extra.forbid

    trackTreasury: bool


class TargetEntrypoint2(BaseModel):
    class Config:
        extra = Extra.forbid

    untrackTreasury: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: TargetEntrypoint | TargetEntrypoint1 | TargetEntrypoint2
    empty: Dict[str, Any]
