# generated by datamodel-codegen:
#   filename:  untrackTreasury.json

from __future__ import annotations

from pydantic import BaseModel


class UntrackTreasuryParameter(BaseModel):
    __root__: str
