# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configTreasuryNameMaxLength: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    empty: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: UpdateConfigAction | UpdateConfigAction1
