# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class LiquidityBakingStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenPool: str
    xtzPool: str
    lqtTotal: str
    tokenAddress: str
    lqtAddress: str
