# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class LiquidityBakingStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenPool: str
    xtzPool: str
    lqtTotal: str
    tokenAddress: str
    lqtAddress: str
