# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class AddLiquidityParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str
    minLqtMinted: str
    maxTokensDeposited: str
    deadline: str
