# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RemoveLiquidityParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to: str
    lqtBurned: str
    minXtzWithdrawn: str
    minTokensWithdrawn: str
    deadline: str
