# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TokenToXtzParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to: str
    tokensSold: str
    minXtzBought: str
    deadline: str
