# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Depositors(BaseModel):
    class Config:
        extra = Extra.forbid

    any: Dict[str, Any]


class Depositors1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: List[str]


class Handle(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class VaultStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    depositors: Depositors | Depositors1
    handle: Handle
    name: str
