# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Depositors(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    any: Dict[str, Any]


class Depositors1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    whitelist: List[str]


class Handle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    owner: str


class VaultStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    depositors: Depositors | Depositors1
    handle: Handle
    name: str
