# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field


class Or(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fakeUsdt: Dict[str, Any]


class Or1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mvn: Dict[str, Any]


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    or_: Or | Or1 = Field(..., alias='or')


class Requester(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Dict[str, Any]


class MvnFaucetStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fakeUsdtAmountPerUser: str
    fakeUsdtTokenAddress: str
    metadata: Dict[str, str]
    mvnAmountPerUser: str
    mvnTokenAddress: str
    requesters: List[Requester]
