# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TargetEntrypointItem(BaseModel):
    class Config:
        extra = Extra.forbid

    compound: bool


class TargetEntrypointItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    farmClaim: bool


class TargetEntrypointItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    onVaultDepositStake: bool


class TargetEntrypointItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    onVaultLiquidateStake: bool


class TargetEntrypointItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    onVaultWithdrawStake: bool


class TargetEntrypointItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    stake: bool


class TargetEntrypointItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    unstake: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: Union[
        TargetEntrypointItem,
        TargetEntrypointItem1,
        TargetEntrypointItem2,
        TargetEntrypointItem3,
        TargetEntrypointItem4,
        TargetEntrypointItem5,
        TargetEntrypointItem6,
    ]
    empty: Dict[str, Any]
