# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    minMvnAmount: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stakeMvnIsPaused: bool
    unstakeMvnIsPaused: bool
    exitIsPaused: bool
    compoundIsPaused: bool
    farmClaimIsPaused: bool
    onVaultDepositStakeIsPaused: bool
    onVaultWithdrawStakeIsPaused: bool
    onVaultLiquidateStakeIsPaused: bool


class UserStakeBalanceLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    balance: str
    totalExitFeeRewardsClaimed: str
    totalSatelliteRewardsClaimed: str
    totalFarmRewardsClaimed: str
    participationFeesPerShare: str


class DoormanStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    userStakeBalanceLedger: Dict[str, UserStakeBalanceLedger]
    unclaimedRewards: str
    accumulatedFeesPerShare: str
    lambdaLedger: Dict[str, str]
