# generated by datamodel-codegen:
#   filename:  updateDepositor.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class DepositorsConfigItem(BaseModel):
    class Config:
        extra = Extra.forbid

    any: Dict[str, Any]


class DepositorsConfigItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: Dict[str, Any]


class UpdateDepositorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    depositorAddress: str
    addOrRemoveBool: bool
    depositorsConfig: Union[DepositorsConfigItem, DepositorsConfigItem1]
