# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra, Field


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    governanceSatelliteApprovalPercentage: str
    governanceSatelliteDurationInDays: str
    governancePurposeMaxLength: str
    maxActionsPerSatellite: str


class GovernanceSatelliteActionLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    initiator: str
    status: bool
    executed: bool
    governanceType: str
    governancePurpose: str
    voters: List[str]
    dataMap: Dict[str, str]
    yayVoteStakedMvkTotal: str
    nayVoteStakedMvkTotal: str
    passVoteStakedMvkTotal: str
    snapshotStakedMvkTotalSupply: str
    stakedMvkPercentageForApproval: str
    stakedMvkRequiredForApproval: str
    startDateTime: str
    expiryDateTime: str


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str


class ValueItem(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class ValueItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class ValueItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class GovernanceSatelliteVoter(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Union[ValueItem, ValueItem1, ValueItem2]


class GovernanceSatelliteStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    actionsInitiators: Dict[str, List[str]]
    admin: str
    aggregatorLedger: Dict[str, str]
    config: Config
    generalContracts: Dict[str, str]
    governanceAddress: str
    governanceSatelliteActionLedger: Dict[str, GovernanceSatelliteActionLedger]
    governanceSatelliteCounter: str
    governanceSatelliteVoters: List[GovernanceSatelliteVoter]
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvkTokenAddress: str
    satelliteAggregatorLedger: Dict[str, Dict[str, str]]
    whitelistContracts: Dict[str, str]
