# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class Tx(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to_: str
    token_id: str
    amount: str


class TransferParameterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: str
    txs: List[Tx]


class TransferParameter(RootModel[List[TransferParameterItem]]):
    root: List[TransferParameterItem]
