# generated by datamodel-codegen:
#   filename:  triggerInflation.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TriggerInflationParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
