# generated by datamodel-codegen:
#   filename:  updateInflationRate.json

from __future__ import annotations

from pydantic import BaseModel


class UpdateInflationRateParameter(BaseModel):
    __root__: str
