# generated by datamodel-codegen:
#   filename:  update_operators.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class AddOperator(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    operator: str
    token_id: str


class UpdateOperatorsParameter1(BaseModel):
    class Config:
        extra = Extra.forbid

    add_operator: AddOperator


class RemoveOperator(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    operator: str
    token_id: str


class UpdateOperatorsParameter2(BaseModel):
    class Config:
        extra = Extra.forbid

    remove_operator: RemoveOperator


class UpdateOperatorsParameter(BaseModel):
    __root__: List[UpdateOperatorsParameter1 | UpdateOperatorsParameter2]
