# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class AddOperator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str
    operator: str
    token_id: str


class UpdateOperatorsParameter1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    add_operator: AddOperator


class RemoveOperator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str
    operator: str
    token_id: str


class UpdateOperatorsParameter2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    remove_operator: RemoveOperator


class UpdateOperatorsParameter(
    RootModel[List[UpdateOperatorsParameter1 | UpdateOperatorsParameter2]]
):
    root: List[UpdateOperatorsParameter1 | UpdateOperatorsParameter2]
