# generated by datamodel-codegen:
#   filename:  pauseAll.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class PauseAllParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
