# generated by datamodel-codegen:
#   filename:  updateData.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class OracleObservations(BaseModel):
    class Config:
        extra = Extra.forbid

    data: str
    epoch: str
    round: str
    aggregatorAddress: str


class UpdateDataParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    oracleObservations: Dict[str, OracleObservations]
    signatures: Dict[str, str]
