# generated by datamodel-codegen:
#   filename:  updateMetadata.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateMetadataParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    metadataKey: str
    metadataHash: str
