# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict


class OracleObservations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    epoch: str
    round: str
    aggregatorAddress: str


class UpdateDataParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oracleObservations: Dict[str, OracleObservations]
    signatures: Dict[str, str]
