# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configAlphaPercentPerThousand: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    configDecimals: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    class Config:
        extra = Extra.forbid

    configHeartbeatSeconds: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    class Config:
        extra = Extra.forbid

    configPercentOracleThreshold: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    class Config:
        extra = Extra.forbid

    configRewardAmountMvrk: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    class Config:
        extra = Extra.forbid

    configRewardAmountStakedMvn: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
    )
