# generated by datamodel-codegen:
#   filename:  updateOracle.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateOracleParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
