# generated by datamodel-codegen:
#   filename:  withdrawRewardStakedMvn.json

from __future__ import annotations

from pydantic import BaseModel


class WithdrawRewardStakedMvnParameter(BaseModel):
    __root__: str
