# generated by datamodel-codegen:
#   filename:  withdrawRewardMvrk.json

from __future__ import annotations

from pydantic import BaseModel


class WithdrawRewardMvrkParameter(BaseModel):
    __root__: str
