# generated by datamodel-codegen:
#   filename:  addVestee.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class AddVesteeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vesteeAddress: str
    totalAllocatedAmount: str
    cliffInMonths: str
    vestingInMonths: str
