# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class AddVesteeParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    vesteeAddress: str
    totalAllocatedAmount: str
    cliffInMonths: str
    vestingInMonths: str
