# generated by datamodel-codegen:
#   filename:  claim.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ClaimParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
