# generated by datamodel-codegen:
#   filename:  toggleVesteeLock.json

from __future__ import annotations

from pydantic import BaseModel


class ToggleVesteeLockParameter(BaseModel):
    __root__: str
