# generated by datamodel-codegen:
#   filename:  updateVestee.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateVesteeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vesteeAddress: str
    newTotalAllocatedAmount: str
    newCliffInMonths: str
    newVestingInMonths: str
