# generated by datamodel-codegen:
#   filename:  updateWhitelistContracts.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateType(BaseModel):
    class Config:
        extra = Extra.forbid

    remove: Dict[str, Any]


class UpdateType1(BaseModel):
    class Config:
        extra = Extra.forbid

    update: Dict[str, Any]


class UpdateWhitelistContractsParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelistContractAddress: str
    updateType: UpdateType | UpdateType1
