# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class GovernanceProxyStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    governanceAddress: str
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvnTokenAddress: str
