# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict


class GovernanceProxyStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    governanceAddress: str
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvnTokenAddress: str
