# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, ConfigDict, Field


class TzbtcStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    big_map: Dict[str, str]
    lambda_: str = Field(..., alias='lambda')
    nat: str
    bool: bool
