# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createVaultIsPaused: bool
    empty: Dict[str, Any]


class VaultFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    vaultCounter: str
    lambdaLedger: Dict[str, str]
    vaultLambdaLedger: Dict[str, str]
