# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decimals: str
    alphaPercentPerThousand: str
    percentOracleThreshold: str
    heartbeatSeconds: str
    rewardAmountStakedMvn: str
    rewardAmountMvrk: str


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateDataIsPaused: bool
    withdrawRewardMvrkIsPaused: bool
    withdrawRewardStakedMvnIsPaused: bool


class OracleLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oraclePublicKey: str
    oraclePeerId: str


class LastCompletedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    round: str
    epoch: str
    data: str
    percentOracleResponse: str
    lastUpdatedAt: str


class AggregatorStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    name: str
    config: Config
    breakGlassConfig: BreakGlassConfig
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    oracleLedger: Dict[str, OracleLedger]
    lastCompletedData: LastCompletedData
    oracleRewardStakedMvn: Dict[str, str]
    oracleRewardMvrk: Dict[str, str]
    lambdaLedger: Dict[str, str]
