# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    alphaPercentPerThousand: str
    percentOracleThreshold: str
    heartbeatSeconds: str
    rewardAmountStakedMvn: str
    rewardAmountMvrk: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    updateDataIsPaused: bool
    withdrawRewardMvrkIsPaused: bool
    withdrawRewardStakedMvnIsPaused: bool


class OracleLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    oraclePublicKey: str
    oraclePeerId: str


class LastCompletedData(BaseModel):
    class Config:
        extra = Extra.forbid

    round: str
    epoch: str
    data: str
    percentOracleResponse: str
    lastUpdatedAt: str


class AggregatorStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    name: str
    config: Config
    breakGlassConfig: BreakGlassConfig
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    oracleLedger: Dict[str, OracleLedger]
    lastCompletedData: LastCompletedData
    oracleRewardStakedMvn: Dict[str, str]
    oracleRewardMvrk: Dict[str, str]
    lambdaLedger: Dict[str, str]
