# generated by datamodel-codegen:
#   filename:  mintOrBurn.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class MintOrBurnParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    quantity: str
    target: str
