# generated by datamodel-codegen:
#   filename:  createFarm.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class PlannedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    totalBlocks: str
    currentRewardPerBlock: str


class TokenStandard(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: Dict[str, Any]


class TokenStandard1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Dict[str, Any]


class LpToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenAddress: str
    tokenId: str
    tokenStandard: TokenStandard | TokenStandard1


class CreateFarmParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    addToGeneralContracts: bool
    forceRewardFromTransfer: bool
    infinite: bool
    plannedRewards: PlannedRewards
    metadata: str
    lpToken: LpToken
