# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class PlannedRewards(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalBlocks: str
    currentRewardPerBlock: str


class TokenStandard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: Dict[str, Any]


class TokenStandard1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Dict[str, Any]


class LpToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenAddress: str
    tokenId: str
    tokenStandard: TokenStandard | TokenStandard1


class CreateFarmParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    addToGeneralContracts: bool
    forceRewardFromTransfer: bool
    infinite: bool
    plannedRewards: PlannedRewards
    metadata: str
    lpToken: LpToken
