# generated by datamodel-codegen:
#   filename:  setProductLambda.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class FarmType(BaseModel):
    class Config:
        extra = Extra.forbid

    farm: Dict[str, Any]


class FarmType1(BaseModel):
    class Config:
        extra = Extra.forbid

    mFarm: Dict[str, Any]


class SetProductLambdaParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    func_bytes: str
    farmType: FarmType | FarmType1
