# generated by datamodel-codegen:
#   filename:  setLambda.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetLambdaParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    func_bytes: str
