# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class FarmType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    farm: Dict[str, Any]


class FarmType1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mFarm: Dict[str, Any]


class SetProductLambdaParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    func_bytes: str
    farmType: FarmType | FarmType1
