# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class TargetEntrypoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createFarm: bool


class TargetEntrypoint1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createFarmMToken: bool


class TargetEntrypoint2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trackFarm: bool


class TargetEntrypoint3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    untrackFarm: bool


class TogglePauseEntrypointParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetEntrypoint: (
        TargetEntrypoint | TargetEntrypoint1 | TargetEntrypoint2 | TargetEntrypoint3
    )
    empty: Dict[str, Any]
