# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    durationInMinutes: str
    minStakedMvnRequiredToTrigger: str
    minStakedMvnRequiredToVote: str
    proposalDescMaxLength: str
    proposalTitleMaxLength: str
    requiredFeeMumav: str
    stakedMvnPercentageRequired: str


class EmergencyGovernanceLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    proposerAddress: str
    executed: bool
    title: str
    description: str
    totalStakedMvnVotes: str
    stakedMvnPercentageRequired: str
    stakedMvnRequiredForBreakGlass: str
    startDateTime: str
    startLevel: str
    executedDateTime: str | None
    executedLevel: str | None
    expirationDateTime: str


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    timestamp: str


class EmergencyGovernanceVoter(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value


class EmergencyGovernanceStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    emergencyGovernanceLedger: Dict[str, EmergencyGovernanceLedger]
    emergencyGovernanceVoters: List[EmergencyGovernanceVoter]
    currentEmergencyGovernanceId: str
    nextEmergencyGovernanceId: str
    lambdaLedger: Dict[str, str]
