# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decimals: str
    durationInMinutes: str
    minStakedMvnRequiredToTrigger: str
    minStakedMvnRequiredToVote: str
    proposalDescMaxLength: str
    proposalTitleMaxLength: str
    requiredFeeMumav: str
    stakedMvnPercentageRequired: str


class EmergencyGovernanceLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposerAddress: str
    executed: bool
    title: str
    description: str
    totalStakedMvnVotes: str
    stakedMvnPercentageRequired: str
    stakedMvnRequiredForBreakGlass: str
    startDateTime: str
    startLevel: str
    executedDateTime: str | None = None
    executedLevel: str | None = None
    expirationDateTime: str


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    address: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    timestamp: str


class EmergencyGovernanceVoter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Value


class EmergencyGovernanceStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    emergencyGovernanceLedger: Dict[str, EmergencyGovernanceLedger]
    emergencyGovernanceVoters: List[EmergencyGovernanceVoter]
    currentEmergencyGovernanceId: str
    nextEmergencyGovernanceId: str
    lambdaLedger: Dict[str, str]
