# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvalPercentage: str
    satelliteActionDurationInDays: str
    governancePurposeMaxLength: str
    maxActionsPerSatellite: str


class GovernanceSatelliteActionLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    initiator: str
    status: bool
    executed: bool
    governanceType: str
    governancePurpose: str
    dataMap: Dict[str, str]
    yayVoteStakedMvnTotal: str
    nayVoteStakedMvnTotal: str
    passVoteStakedMvnTotal: str
    governanceCycleId: str
    snapshotStakedMvnTotalSupply: str
    stakedMvnPercentageForApproval: str
    stakedMvnRequiredForApproval: str
    startDateTime: str
    expiryDateTime: str
    executedDateTime: str | None = None


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    address: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nay: Dict[str, Any]


class Value1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pass_: Dict[str, Any] = Field(..., alias='pass')


class Value2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    yay: Dict[str, Any]


class GovernanceSatelliteVoter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Value | Value1 | Value2


class SatelliteAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: List[str]


class GovernanceSatelliteStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    aggregatorLedger: Dict[str, str]
    config: Config
    generalContracts: Dict[str, str]
    governanceAddress: str
    governanceSatelliteActionLedger: Dict[str, GovernanceSatelliteActionLedger]
    governanceSatelliteCounter: str
    governanceSatelliteVoters: List[GovernanceSatelliteVoter]
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvnTokenAddress: str
    satelliteActions: List[SatelliteAction]
    satelliteAggregatorLedger: Dict[str, Dict[str, str]]
    whitelistContracts: Dict[str, Dict[str, Any]]
