# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra, Field


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    approvalPercentage: str
    satelliteActionDurationInDays: str
    governancePurposeMaxLength: str
    maxActionsPerSatellite: str


class GovernanceSatelliteActionLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    initiator: str
    status: bool
    executed: bool
    governanceType: str
    governancePurpose: str
    dataMap: Dict[str, str]
    yayVoteStakedMvnTotal: str
    nayVoteStakedMvnTotal: str
    passVoteStakedMvnTotal: str
    governanceCycleId: str
    snapshotStakedMvnTotalSupply: str
    stakedMvnPercentageForApproval: str
    stakedMvnRequiredForApproval: str
    startDateTime: str
    expiryDateTime: str
    executedDateTime: str | None


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class Value1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class Value2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class GovernanceSatelliteVoter(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value | Value1 | Value2


class SatelliteAction(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: List[str]


class GovernanceSatelliteStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    aggregatorLedger: Dict[str, str]
    config: Config
    generalContracts: Dict[str, str]
    governanceAddress: str
    governanceSatelliteActionLedger: Dict[str, GovernanceSatelliteActionLedger]
    governanceSatelliteCounter: str
    governanceSatelliteVoters: List[GovernanceSatelliteVoter]
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvnTokenAddress: str
    satelliteActions: List[SatelliteAction]
    satelliteAggregatorLedger: Dict[str, Dict[str, str]]
    whitelistContracts: Dict[str, Dict[str, Any]]
