# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel, Extra


class DepositorsConfigItem(BaseModel):
    class Config:
        extra = Extra.forbid

    any: Dict[str, Any]


class DepositorsConfigItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: Dict[str, Any]


class Depositors(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelistedDepositors: List[str]
    depositorsConfig: Union[DepositorsConfigItem, DepositorsConfigItem1]


class Handle(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class VaultStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    depositors: Depositors
    governanceAddress: str
    handle: Handle
    lambdaLedger: Dict[str, str]
    metadata: Dict[str, str]
    mvkTokenAddress: str
