# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvalPercentage: str
    financialRequestDurationInDays: str


class FinancialRequestLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requesterAddress: str
    requestType: str
    status: bool
    executed: bool
    treasuryAddress: str
    receiverAddress: str
    tokenContractAddress: str
    tokenAmount: str
    tokenName: str
    tokenType: str
    tokenId: str
    requestPurpose: str
    keyHash: str | None = None
    yayVoteStakedMvnTotal: str
    nayVoteStakedMvnTotal: str
    passVoteStakedMvnTotal: str
    governanceCycleId: str
    snapshotStakedMvnTotalSupply: str
    stakedMvnPercentageForApproval: str
    stakedMvnRequiredForApproval: str
    requestedDateTime: str
    expiryDateTime: str
    executedDateTime: str | None = None


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    address: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nay: Dict[str, Any]


class Value1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pass_: Dict[str, Any] = Field(..., alias='pass')


class Value2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    yay: Dict[str, Any]


class FinancialRequestVoter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Value | Value1 | Value2


class GovernanceFinancialStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistTokenContracts: Dict[str, Dict[str, Any]]
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    financialRequestLedger: Dict[str, FinancialRequestLedger]
    financialRequestCounter: str
    financialRequestVoters: List[FinancialRequestVoter]
    lambdaLedger: Dict[str, str]
