# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra, Field


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    approvalPercentage: str
    financialRequestDurationInDays: str


class FinancialRequestLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    requesterAddress: str
    requestType: str
    status: bool
    executed: bool
    treasuryAddress: str
    receiverAddress: str
    tokenContractAddress: str
    tokenAmount: str
    tokenName: str
    tokenType: str
    tokenId: str
    requestPurpose: str
    keyHash: str | None
    yayVoteStakedMvnTotal: str
    nayVoteStakedMvnTotal: str
    passVoteStakedMvnTotal: str
    governanceCycleId: str
    snapshotStakedMvnTotalSupply: str
    stakedMvnPercentageForApproval: str
    stakedMvnRequiredForApproval: str
    requestedDateTime: str
    expiryDateTime: str
    executedDateTime: str | None


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class Value1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class Value2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class FinancialRequestVoter(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value | Value1 | Value2


class GovernanceFinancialStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistTokenContracts: Dict[str, Dict[str, Any]]
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    financialRequestLedger: Dict[str, FinancialRequestLedger]
    financialRequestCounter: str
    financialRequestVoters: List[FinancialRequestVoter]
    lambdaLedger: Dict[str, str]
