# generated by datamodel-codegen:
#   filename:  updateDepositor.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class Allowance(BaseModel):
    class Config:
        extra = Extra.forbid

    any: bool


class Whitelist(BaseModel):
    class Config:
        extra = Extra.forbid

    bool: bool
    address: str


class Allowance1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: Whitelist


class UpdateDepositorParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    allowance: Allowance | Allowance1
    empty: Dict[str, Any]
