# generated by datamodel-codegen:
#   filename:  updateVaultName.json

from __future__ import annotations

from pydantic import BaseModel


class UpdateVaultNameParameter(BaseModel):
    __root__: str
