# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class Allowance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    any: bool


class Whitelist(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bool: bool
    address: str


class Allowance1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    whitelist: Whitelist


class UpdateDepositorParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowance: Allowance | Allowance1
    empty: Dict[str, Any]
