# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class UpdateConfigAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configDurationInMinutes: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinStakedMvnForVoting: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinStakedMvnToTrigger: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configProposalDescMaxLength: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configProposalTitleMaxLength: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configRequiredFeeMumav: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configStakedMvnPercentRequired: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
    )
