# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configDurationInMinutes: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinStakedMvnForVoting: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinStakedMvnToTrigger: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposalDescMaxLength: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposalTitleMaxLength: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    class Config:
        extra = Extra.forbid

    configRequiredFeeMumav: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    class Config:
        extra = Extra.forbid

    configStakedMvnPercentRequired: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
    )
