# generated by datamodel-codegen:
#   filename:  voteForEmergencyControl.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class VoteForEmergencyControlParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
