# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CouncilActionChangeMemberParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oldCouncilMemberAddress: str
    newCouncilMemberAddress: str
    newCouncilMemberName: str
    newCouncilMemberWebsite: str
    newCouncilMemberImage: str
