# generated by datamodel-codegen:
#   filename:  pauseAllEntrypoints.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class PauseAllEntrypointsParameter(BaseModel):
    __root__: List[str]
