# generated by datamodel-codegen:
#   filename:  propagateBreakGlass.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class PropagateBreakGlassParameter(BaseModel):
    __root__: List[str]
