# generated by datamodel-codegen:
#   filename:  removeBreakGlassControl.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class RemoveBreakGlassControlParameter(BaseModel):
    __root__: List[str]
