# generated by datamodel-codegen:
#   filename:  setContractsAdmin.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class SetContractsAdminParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    contractAddressSet: List[str]
    newAdminAddress: str
