# generated by datamodel-codegen:
#   filename:  unpauseAllEntrypoints.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class UnpauseAllEntrypointsParameter(BaseModel):
    __root__: List[str]
