# generated by datamodel-codegen:
#   filename:  updateCouncilMemberInfo.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateCouncilMemberInfoParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    website: str
    image: str
