# generated by datamodel-codegen:
#   filename:  compound.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class CompoundParameter(BaseModel):
    __root__: List[str]
