# generated by datamodel-codegen:
#   filename:  exit.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ExitParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
