# generated by datamodel-codegen:
#   filename:  farmClaim.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class SetItem(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class FarmClaimParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    set: List[SetItem]
    bool: bool
