# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class SetItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    nat: str


class FarmClaimParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    set: List[SetItem]
    bool: bool
