# generated by datamodel-codegen:
#   filename:  onVaultLiquidateStake.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OnVaultLiquidateStakeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultAddress: str
    liquidator: str
    liquidatedAmount: str
