# generated by datamodel-codegen:
#   filename:  onVaultDepositStake.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OnVaultDepositStakeParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultOwner: str
    vaultAddress: str
    depositAmount: str
