# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TargetEntrypoint(BaseModel):
    class Config:
        extra = Extra.forbid

    compound: bool


class TargetEntrypoint1(BaseModel):
    class Config:
        extra = Extra.forbid

    exit: bool


class TargetEntrypoint2(BaseModel):
    class Config:
        extra = Extra.forbid

    farmClaim: bool


class TargetEntrypoint3(BaseModel):
    class Config:
        extra = Extra.forbid

    onVaultDepositStake: bool


class TargetEntrypoint4(BaseModel):
    class Config:
        extra = Extra.forbid

    onVaultLiquidateStake: bool


class TargetEntrypoint5(BaseModel):
    class Config:
        extra = Extra.forbid

    onVaultWithdrawStake: bool


class TargetEntrypoint6(BaseModel):
    class Config:
        extra = Extra.forbid

    stakeMvn: bool


class TargetEntrypoint7(BaseModel):
    class Config:
        extra = Extra.forbid

    unstakeMvn: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: (
        TargetEntrypoint
        | TargetEntrypoint1
        | TargetEntrypoint2
        | TargetEntrypoint3
        | TargetEntrypoint4
        | TargetEntrypoint5
        | TargetEntrypoint6
        | TargetEntrypoint7
    )
    empty: Dict[str, Any]
