# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    treasuryNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createTreasuryIsPaused: bool
    trackTreasuryIsPaused: bool
    untrackTreasuryIsPaused: bool


class TreasuryFactoryStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    trackedTreasuries: List[str]
    breakGlassConfig: BreakGlassConfig
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, Dict[str, Any]]
    lambdaLedger: Dict[str, str]
    treasuryLambdaLedger: Dict[str, str]
