# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    treasuryNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createTreasuryIsPaused: bool
    trackTreasuryIsPaused: bool
    untrackTreasuryIsPaused: bool


class TreasuryFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    trackedTreasuries: List[str]
    breakGlassConfig: BreakGlassConfig
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, Dict[str, Any]]
    lambdaLedger: Dict[str, str]
    treasuryLambdaLedger: Dict[str, str]
