# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_id: str
    token_info: Dict[str, str]


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Dict[str, Any]


class MTokenStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    loanToken: str
    isScaledToken: bool
    tokenRewardIndex: str
    rewardIndexLedger: Dict[str, str]
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    token_metadata: Dict[str, TokenMetadata]
    totalSupply: str
    ledger: Dict[str, str]
    operators: List[Operator]
