# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    transferIsPaused: bool
    mintMvnAndTransferIsPaused: bool
    updateTokenOperatorsIsPaused: bool
    stakeTokensIsPaused: bool
    unstakeTokensIsPaused: bool


class TreasuryStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    name: str
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, Dict[str, Any]]
    breakGlassConfig: BreakGlassConfig
    lambdaLedger: Dict[str, str]
