# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    transferIsPaused: bool
    mintMvnAndTransferIsPaused: bool
    updateTokenOperatorsIsPaused: bool
    stakeTokensIsPaused: bool
    unstakeTokensIsPaused: bool


class TreasuryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    name: str
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, Dict[str, Any]]
    breakGlassConfig: BreakGlassConfig
    lambdaLedger: Dict[str, str]
