# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class TokenStandard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: Dict[str, Any]


class TokenStandard1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Dict[str, Any]


class LpToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenAddress: str
    tokenId: str
    tokenStandard: TokenStandard | TokenStandard1
    tokenBalance: str


class PlannedRewards(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalBlocks: str
    currentRewardPerBlock: str
    totalRewards: str


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    forceRewardFromTransfer: bool
    infinite: bool
    loanToken: str
    lpToken: LpToken
    plannedRewards: PlannedRewards


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    depositIsPaused: bool
    withdrawIsPaused: bool
    claimIsPaused: bool


class ClaimedRewards(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unpaid: str
    paid: str


class DepositorLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    balance: str
    participationRewardsPerShare: str
    tokenRewardIndex: str
    unclaimedRewards: str
    claimedRewards: str


class MFarmStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    name: str
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    lastBlockUpdate: str
    accumulatedRewardsPerShare: str
    claimedRewards: ClaimedRewards
    depositorLedger: Dict[str, DepositorLedger]
    open: bool
    init: bool
    initBlock: str
    minBlockTimeSnapshot: str
    lambdaLedger: Dict[str, str]
