# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TokenStandard(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: Dict[str, Any]


class TokenStandard1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Dict[str, Any]


class LpToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenAddress: str
    tokenId: str
    tokenStandard: TokenStandard | TokenStandard1
    tokenBalance: str


class PlannedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    totalBlocks: str
    currentRewardPerBlock: str
    totalRewards: str


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    forceRewardFromTransfer: bool
    infinite: bool
    loanToken: str
    lpToken: LpToken
    plannedRewards: PlannedRewards


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    depositIsPaused: bool
    withdrawIsPaused: bool
    claimIsPaused: bool


class ClaimedRewards(BaseModel):
    class Config:
        extra = Extra.forbid

    unpaid: str
    paid: str


class DepositorLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    balance: str
    participationRewardsPerShare: str
    tokenRewardIndex: str
    unclaimedRewards: str
    claimedRewards: str


class MFarmStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    name: str
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    lastBlockUpdate: str
    accumulatedRewardsPerShare: str
    claimedRewards: ClaimedRewards
    depositorLedger: Dict[str, DepositorLedger]
    open: bool
    init: bool
    initBlock: str
    minBlockTimeSnapshot: str
    lambdaLedger: Dict[str, str]
