# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    minimumStakedMvnBalance: str
    delegationRatio: str
    maxSatellites: str
    satelliteNameMaxLength: str
    satelliteDescriptionMaxLength: str
    satelliteImageMaxLength: str
    satelliteWebsiteMaxLength: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    delegateToSatelliteIsPaused: bool
    distributeRewardIsPaused: bool
    registerAsSatelliteIsPaused: bool
    takeSatellitesSnapshotPaused: bool
    undelegateFromSatelliteIsPaused: bool
    unregisterAsSatelliteIsPaused: bool
    updateSatelliteRecordIsPaused: bool


class DelegateLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteAddress: str
    satelliteRegisteredDateTime: str
    delegatedDateTime: str
    delegatedStakedMvnBalance: str


class SatelliteLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    status: str
    stakedMvnBalance: str
    satelliteFee: str
    totalDelegatedAmount: str
    name: str
    description: str
    image: str
    website: str
    registeredDateTime: str
    oraclePublicKey: str
    oraclePeerId: str


class SatelliteRewardsLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    unpaid: str
    paid: str
    participationRewardsPerShare: str
    satelliteAccumulatedRewardsPerShare: str
    satelliteReferenceAddress: str
    referenceGovernanceCycleId: str
    tracked: bool


class DelegationStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    delegateLedger: Dict[str, DelegateLedger]
    satelliteLedger: Dict[str, SatelliteLedger]
    satelliteCounter: str
    satelliteRewardsLedger: Dict[str, SatelliteRewardsLedger]
    lambdaLedger: Dict[str, str]
