# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    minimumStakedMvnBalance: str
    delegationRatio: str
    maxSatellites: str
    satelliteNameMaxLength: str
    satelliteDescriptionMaxLength: str
    satelliteImageMaxLength: str
    satelliteWebsiteMaxLength: str


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    delegateToSatelliteIsPaused: bool
    distributeRewardIsPaused: bool
    registerAsSatelliteIsPaused: bool
    takeSatellitesSnapshotPaused: bool
    undelegateFromSatelliteIsPaused: bool
    unregisterAsSatelliteIsPaused: bool
    updateSatelliteRecordIsPaused: bool


class DelegateLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    satelliteAddress: str
    satelliteRegisteredDateTime: str
    delegatedDateTime: str
    delegatedStakedMvnBalance: str


class SatelliteLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str
    stakedMvnBalance: str
    satelliteFee: str
    totalDelegatedAmount: str
    name: str
    description: str
    image: str
    website: str
    registeredDateTime: str
    oraclePublicKey: str
    oraclePeerId: str


class SatelliteRewardsLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unpaid: str
    paid: str
    participationRewardsPerShare: str
    satelliteAccumulatedRewardsPerShare: str
    satelliteReferenceAddress: str
    referenceGovernanceCycleId: str
    tracked: bool


class DelegationStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    delegateLedger: Dict[str, DelegateLedger]
    satelliteLedger: Dict[str, SatelliteLedger]
    satelliteCounter: str
    satelliteRewardsLedger: Dict[str, SatelliteRewardsLedger]
    lambdaLedger: Dict[str, str]
