# generated by datamodel-codegen:
#   filename:  requestFakeUsdt.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RequestFakeUsdtParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
