# generated by datamodel-codegen:
#   filename:  requestMvn.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RequestMvnParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
