# generated by datamodel-codegen:
#   filename:  councilActionRemoveVestee.json

from __future__ import annotations

from pydantic import BaseModel


class CouncilActionRemoveVesteeParameter(BaseModel):
    __root__: str
