# generated by datamodel-codegen:
#   filename:  councilActionTransfer.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CouncilActionTransferParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    receiverAddress: str
    tokenContractAddress: str
    tokenAmount: str
    tokenType: str
    tokenId: str
    purpose: str
