# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CouncilActionAddMemberParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memberAddress: str
    memberName: str
    memberWebsite: str
    memberImage: str
