# generated by datamodel-codegen:
#   filename:  councilActionToggleVesteeLock.json

from __future__ import annotations

from pydantic import BaseModel


class CouncilActionToggleVesteeLockParameter(BaseModel):
    __root__: str
