# generated by datamodel-codegen:
#   filename:  councilActionDropFinancialReq.json

from __future__ import annotations

from pydantic import BaseModel


class CouncilActionDropFinancialReqParameter(BaseModel):
    __root__: str
