# generated by datamodel-codegen:
#   filename:  councilActionSetContractBaker.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CouncilActionSetContractBakerParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetContractAddress: str
    keyHash: str | None
