# generated by datamodel-codegen:
#   filename:  councilActionRemoveMember.json

from __future__ import annotations

from pydantic import BaseModel


class CouncilActionRemoveMemberParameter(BaseModel):
    __root__: str
