# generated by datamodel-codegen:
#   filename:  councilActionSetBaker.json

from __future__ import annotations

from pydantic import BaseModel


class CouncilActionSetBakerParameter(BaseModel):
    __root__: str | None
