# generated by datamodel-codegen:
#   filename:  councilActionRequestMint.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CouncilActionRequestMintParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    treasuryAddress: str
    receiverAddress: str
    tokenAmount: str
    purpose: str
