# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CouncilActionRequestMintParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    treasuryAddress: str
    receiverAddress: str
    tokenAmount: str
    purpose: str
