# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configActionExpiryDays: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    configCouncilImageMaxLength: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    class Config:
        extra = Extra.forbid

    configCouncilNameMaxLength: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    class Config:
        extra = Extra.forbid

    configCouncilWebsiteMaxLength: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    class Config:
        extra = Extra.forbid

    configRequestPurposeMaxLength: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    class Config:
        extra = Extra.forbid

    configRequestTokenNameMaxLength: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    class Config:
        extra = Extra.forbid

    configThreshold: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
    )
