# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, ConfigDict


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str
    spender: str


class Allowance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: str


class SiriusStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokens: Dict[str, str]
    allowances: List[Allowance]
    admin: str
    total_supply: str
