# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    spender: str


class Allowance(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: str


class SiriusStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    tokens: Dict[str, str]
    allowances: List[Allowance]
    admin: str
    total_supply: str
