# generated by datamodel-codegen:
#   filename:  delegateToSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class DelegateToSatelliteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    userAddress: str
    satelliteAddress: str
