# generated by datamodel-codegen:
#   filename:  distributeReward.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class DistributeRewardParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    eligibleSatellites: List[str]
    totalStakedMvnReward: str
