# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class DistributeRewardParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eligibleSatellites: List[str]
    totalStakedMvnReward: str
