# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class OnStakeChangeParameterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    nat: str


class OnStakeChangeParameter(RootModel[List[OnStakeChangeParameterItem]]):
    root: List[OnStakeChangeParameterItem]
