# generated by datamodel-codegen:
#   filename:  registerAsSatellite.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RegisterAsSatelliteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    description: str
    image: str
    website: str
    satelliteFee: str
    oraclePublicKey: str | None
    oraclePeerId: str | None
