# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class TargetEntrypoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    delegateToSatellite: bool


class TargetEntrypoint1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    distributeReward: bool


class TargetEntrypoint2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    registerAsSatellite: bool


class TargetEntrypoint3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    takeSatellitesSnapshot: bool


class TargetEntrypoint4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    undelegateFromSatellite: bool


class TargetEntrypoint5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unregisterAsSatellite: bool


class TargetEntrypoint6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateSatelliteRecord: bool


class TogglePauseEntrypointParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    targetEntrypoint: (
        TargetEntrypoint
        | TargetEntrypoint1
        | TargetEntrypoint2
        | TargetEntrypoint3
        | TargetEntrypoint4
        | TargetEntrypoint5
        | TargetEntrypoint6
    )
    empty: Dict[str, Any]
