# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TargetEntrypoint(BaseModel):
    class Config:
        extra = Extra.forbid

    delegateToSatellite: bool


class TargetEntrypoint1(BaseModel):
    class Config:
        extra = Extra.forbid

    distributeReward: bool


class TargetEntrypoint2(BaseModel):
    class Config:
        extra = Extra.forbid

    registerAsSatellite: bool


class TargetEntrypoint3(BaseModel):
    class Config:
        extra = Extra.forbid

    takeSatellitesSnapshot: bool


class TargetEntrypoint4(BaseModel):
    class Config:
        extra = Extra.forbid

    undelegateFromSatellite: bool


class TargetEntrypoint5(BaseModel):
    class Config:
        extra = Extra.forbid

    unregisterAsSatellite: bool


class TargetEntrypoint6(BaseModel):
    class Config:
        extra = Extra.forbid

    updateSatelliteRecord: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: (
        TargetEntrypoint
        | TargetEntrypoint1
        | TargetEntrypoint2
        | TargetEntrypoint3
        | TargetEntrypoint4
        | TargetEntrypoint5
        | TargetEntrypoint6
    )
    empty: Dict[str, Any]
