# generated by datamodel-codegen:
#   filename:  undelegateFromSatellite.json

from __future__ import annotations

from pydantic import BaseModel


class UndelegateFromSatelliteParameter(BaseModel):
    __root__: str
