# generated by datamodel-codegen:
#   filename:  unregisterAsSatellite.json

from __future__ import annotations

from pydantic import BaseModel


class UnregisterAsSatelliteParameter(BaseModel):
    __root__: str
