# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class UpdateConfigAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configDelegationRatio: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMaxSatellites: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinimumStakedMvnBalance: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configSatDescMaxLength: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configSatImageMaxLength: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configSatNameMaxLength: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configSatWebsiteMaxLength: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
    )
