# generated by datamodel-codegen:
#   filename:  updateSatelliteStatus.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateSatelliteStatusParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteAddress: str
    newStatus: str
