# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configDelegationRatio: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxSatellites: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinimumStakedMvnBalance: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    class Config:
        extra = Extra.forbid

    configSatDescMaxLength: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    class Config:
        extra = Extra.forbid

    configSatImageMaxLength: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    class Config:
        extra = Extra.forbid

    configSatNameMaxLength: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    class Config:
        extra = Extra.forbid

    configSatWebsiteMaxLength: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
    )
