# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class UpdateSatelliteRecordParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    description: str
    image: str
    website: str
    satelliteFee: str
    oraclePublicKey: str | None = None
    oraclePeerId: str | None = None
