# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Dict[str, Any]


class TokenMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    token_id: str
    token_info: Dict[str, str]


class MvnTokenStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    generalContracts: Dict[str, str]
    governanceAddress: str
    inflationRate: str
    ledger: Dict[str, str]
    maximumSupply: str
    metadata: Dict[str, str]
    nextInflationTimestamp: str
    operators: List[Operator]
    token_metadata: Dict[str, TokenMetadata]
    totalSupply: str
    whitelistContracts: Dict[str, Dict[str, Any]]
