# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Dict[str, Any]


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_id: str
    token_info: Dict[str, str]


class MvnTokenStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    generalContracts: Dict[str, str]
    governanceAddress: str
    inflationRate: str
    ledger: Dict[str, str]
    maximumSupply: str
    metadata: Dict[str, str]
    nextInflationTimestamp: str
    operators: List[Operator]
    token_metadata: Dict[str, TokenMetadata]
    totalSupply: str
    whitelistContracts: Dict[str, Dict[str, Any]]
