# generated by datamodel-codegen:
#   filename:  vaultDepositStakedToken.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class VaultDepositStakedTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    vaultId: str
    depositAmount: str
