# generated by datamodel-codegen:
#   filename:  setLoanToken.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TokenType(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenType1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenType2(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class CreateLoanToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenDecimals: str
    oracleAddress: str
    mTokenAddress: str
    reserveRatio: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    minRepaymentAmount: str
    tokenType: TokenType | TokenType1 | TokenType2


class Action(BaseModel):
    class Config:
        extra = Extra.forbid

    createLoanToken: CreateLoanToken


class UpdateLoanToken(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    oracleAddress: str
    reserveRatio: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    minRepaymentAmount: str
    isPaused: bool


class Action1(BaseModel):
    class Config:
        extra = Extra.forbid

    updateLoanToken: UpdateLoanToken


class SetLoanTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    action: Action | Action1
    empty: Dict[str, Any]
