# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class TargetEntrypoint(BaseModel):
    class Config:
        extra = Extra.forbid

    addLiquidity: bool


class TargetEntrypoint1(BaseModel):
    class Config:
        extra = Extra.forbid

    borrow: bool


class TargetEntrypoint2(BaseModel):
    class Config:
        extra = Extra.forbid

    closeVault: bool


class TargetEntrypoint3(BaseModel):
    class Config:
        extra = Extra.forbid

    liquidateVault: bool


class TargetEntrypoint4(BaseModel):
    class Config:
        extra = Extra.forbid

    markForLiquidation: bool


class TargetEntrypoint5(BaseModel):
    class Config:
        extra = Extra.forbid

    registerDeposit: bool


class TargetEntrypoint6(BaseModel):
    class Config:
        extra = Extra.forbid

    registerVaultCreation: bool


class TargetEntrypoint7(BaseModel):
    class Config:
        extra = Extra.forbid

    registerWithdrawal: bool


class TargetEntrypoint8(BaseModel):
    class Config:
        extra = Extra.forbid

    removeLiquidity: bool


class TargetEntrypoint9(BaseModel):
    class Config:
        extra = Extra.forbid

    repay: bool


class TargetEntrypoint10(BaseModel):
    class Config:
        extra = Extra.forbid

    setCollateralToken: bool


class TargetEntrypoint11(BaseModel):
    class Config:
        extra = Extra.forbid

    setLoanToken: bool


class TargetEntrypoint12(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultDeposit: bool


class TargetEntrypoint13(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultDepositStakedToken: bool


class TargetEntrypoint14(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultOnLiquidate: bool


class TargetEntrypoint15(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultWithdraw: bool


class TargetEntrypoint16(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultWithdrawStakedToken: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: (
        TargetEntrypoint
        | TargetEntrypoint1
        | TargetEntrypoint2
        | TargetEntrypoint3
        | TargetEntrypoint4
        | TargetEntrypoint5
        | TargetEntrypoint6
        | TargetEntrypoint7
        | TargetEntrypoint8
        | TargetEntrypoint9
        | TargetEntrypoint10
        | TargetEntrypoint11
        | TargetEntrypoint12
        | TargetEntrypoint13
        | TargetEntrypoint14
        | TargetEntrypoint15
        | TargetEntrypoint16
    )
    empty: Dict[str, Any]
