# generated by datamodel-codegen:
#   filename:  togglePauseEntrypoint.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel, Extra


class TargetEntrypointItem(BaseModel):
    class Config:
        extra = Extra.forbid

    addLiquidity: bool


class TargetEntrypointItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    borrow: bool


class TargetEntrypointItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    closeVault: bool


class TargetEntrypointItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    liquidateVault: bool


class TargetEntrypointItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    markForLiquidation: bool


class TargetEntrypointItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    registerDeposit: bool


class TargetEntrypointItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    registerVaultCreation: bool


class TargetEntrypointItem7(BaseModel):
    class Config:
        extra = Extra.forbid

    registerWithdrawal: bool


class TargetEntrypointItem8(BaseModel):
    class Config:
        extra = Extra.forbid

    removeLiquidity: bool


class TargetEntrypointItem9(BaseModel):
    class Config:
        extra = Extra.forbid

    repay: bool


class TargetEntrypointItem10(BaseModel):
    class Config:
        extra = Extra.forbid

    setCollateralToken: bool


class TargetEntrypointItem11(BaseModel):
    class Config:
        extra = Extra.forbid

    setLoanToken: bool


class TargetEntrypointItem12(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultDeposit: bool


class TargetEntrypointItem13(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultDepositStakedToken: bool


class TargetEntrypointItem14(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultOnLiquidate: bool


class TargetEntrypointItem15(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultWithdraw: bool


class TargetEntrypointItem16(BaseModel):
    class Config:
        extra = Extra.forbid

    vaultWithdrawStakedToken: bool


class TogglePauseEntrypointParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    targetEntrypoint: Union[
        TargetEntrypointItem,
        TargetEntrypointItem1,
        TargetEntrypointItem2,
        TargetEntrypointItem3,
        TargetEntrypointItem4,
        TargetEntrypointItem5,
        TargetEntrypointItem6,
        TargetEntrypointItem7,
        TargetEntrypointItem8,
        TargetEntrypointItem9,
        TargetEntrypointItem10,
        TargetEntrypointItem11,
        TargetEntrypointItem12,
        TargetEntrypointItem13,
        TargetEntrypointItem14,
        TargetEntrypointItem15,
        TargetEntrypointItem16,
    ]
    empty: Dict[str, Any]
