# generated by datamodel-codegen:
#   filename:  vaultWithdrawStakedToken.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class VaultWithdrawStakedTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    vaultId: str
    withdrawAmount: str
