# generated by datamodel-codegen:
#   filename:  breakGlass.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BreakGlassParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
