# generated by datamodel-codegen:
#   filename:  distributeProposalRewards.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class DistributeProposalRewardsParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    satelliteAddress: str
    proposalIds: List[str]
