# generated by DipDup 8.0.0

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class DistributeProposalRewardsParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    satelliteAddress: str
    proposalIds: List[str]
