# generated by datamodel-codegen:
#   filename:  executeProposal.json

from __future__ import annotations

from pydantic import BaseModel


class ExecuteProposalParameter(BaseModel):
    __root__: str
