# generated by datamodel-codegen:
#   filename:  processProposalPayment.json

from __future__ import annotations

from pydantic import BaseModel


class ProcessProposalPaymentParameter(BaseModel):
    __root__: str
