# generated by datamodel-codegen:
#   filename:  processProposalSingleData.json

from __future__ import annotations

from pydantic import BaseModel


class ProcessProposalSingleDataParameter(BaseModel):
    __root__: str
