# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class AddOrSetProposalData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    encodedCode: str
    codeDescription: str | None = None
    index: str | None = None


class ProposalData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addOrSetProposalData: AddOrSetProposalData


class ProposalData1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    removeProposalData: str


class Token(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenContractAddress: str
    tokenId: str


class Token1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Fa2


class Token2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mav: Dict[str, Any]


class Transaction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to_: str
    amount: str
    token: Token | Token1 | Token2


class AddOrSetPaymentData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    transaction: Transaction
    index: str | None = None


class PaymentData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addOrSetPaymentData: AddOrSetPaymentData


class PaymentData1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    removePaymentData: str


class ProposeParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    description: str
    invoice: str
    sourceCode: str
    proposalData: List[ProposalData | ProposalData1] | None = None
    paymentData: List[PaymentData | PaymentData1] | None = None
