# generated by datamodel-codegen:
#   filename:  proposalRoundVote.json

from __future__ import annotations

from pydantic import BaseModel


class ProposalRoundVoteParameter(BaseModel):
    __root__: str
