# generated by datamodel-codegen:
#   filename:  setGovernanceProxy.json

from __future__ import annotations

from pydantic import BaseModel


class SetGovernanceProxyParameter(BaseModel):
    __root__: str
