# generated by datamodel-codegen:
#   filename:  startNextRound.json

from __future__ import annotations

from pydantic import BaseModel


class StartNextRoundParameter(BaseModel):
    __root__: bool
