# generated by datamodel-codegen:
#   filename:  updateProposalData.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class AddOrSetProposalData(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    encodedCode: str
    codeDescription: str | None
    index: str | None


class ProposalData(BaseModel):
    class Config:
        extra = Extra.forbid

    addOrSetProposalData: AddOrSetProposalData


class ProposalData1(BaseModel):
    class Config:
        extra = Extra.forbid

    removeProposalData: str


class Token(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class Token1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class Token2(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class Transaction(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    amount: str
    token: Token | Token1 | Token2


class AddOrSetPaymentData(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    transaction: Transaction
    index: str | None


class PaymentData(BaseModel):
    class Config:
        extra = Extra.forbid

    addOrSetPaymentData: AddOrSetPaymentData


class PaymentData1(BaseModel):
    class Config:
        extra = Extra.forbid

    removePaymentData: str


class UpdateProposalDataParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    proposalId: str
    proposalData: List[ProposalData | ProposalData1] | None
    paymentData: List[PaymentData | PaymentData1] | None
