# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, ConfigDict


class UpdateConfigAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configBlocksPerProposalRound: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configBlocksPerTimelockRound: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configBlocksPerVotingRound: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configCycleVotersReward: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configDataTitleMaxLength: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMaxProposalsPerSatellite: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinProposalRoundVotePct: Dict[str, Any]


class UpdateConfigAction7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinQuorumPercentage: Dict[str, Any]


class UpdateConfigAction8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configMinYayVotePercentage: Dict[str, Any]


class UpdateConfigAction9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configProposalCodeMaxLength: Dict[str, Any]


class UpdateConfigAction10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configProposalDescMaxLength: Dict[str, Any]


class UpdateConfigAction11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configProposalInvoiceMaxLength: Dict[str, Any]


class UpdateConfigAction12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configProposalTitleMaxLength: Dict[str, Any]


class UpdateConfigAction13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configProposeFeeMumav: Dict[str, Any]


class UpdateConfigAction14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    configSuccessReward: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
        | UpdateConfigAction7
        | UpdateConfigAction8
        | UpdateConfigAction9
        | UpdateConfigAction10
        | UpdateConfigAction11
        | UpdateConfigAction12
        | UpdateConfigAction13
        | UpdateConfigAction14
    )
