# generated by datamodel-codegen:
#   filename:  updateWhitelistDevelopers.json

from __future__ import annotations

from pydantic import BaseModel


class UpdateWhitelistDevelopersParameter(BaseModel):
    __root__: str
