# generated by datamodel-codegen:
#   filename:  updateConfig.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra


class UpdateConfigAction(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerProposalRound: Dict[str, Any]


class UpdateConfigAction1(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerTimelockRound: Dict[str, Any]


class UpdateConfigAction2(BaseModel):
    class Config:
        extra = Extra.forbid

    configBlocksPerVotingRound: Dict[str, Any]


class UpdateConfigAction3(BaseModel):
    class Config:
        extra = Extra.forbid

    configCycleVotersReward: Dict[str, Any]


class UpdateConfigAction4(BaseModel):
    class Config:
        extra = Extra.forbid

    configDataTitleMaxLength: Dict[str, Any]


class UpdateConfigAction5(BaseModel):
    class Config:
        extra = Extra.forbid

    configMaxProposalsPerSatellite: Dict[str, Any]


class UpdateConfigAction6(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinProposalRoundVotePct: Dict[str, Any]


class UpdateConfigAction7(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinQuorumPercentage: Dict[str, Any]


class UpdateConfigAction8(BaseModel):
    class Config:
        extra = Extra.forbid

    configMinYayVotePercentage: Dict[str, Any]


class UpdateConfigAction9(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposalCodeMaxLength: Dict[str, Any]


class UpdateConfigAction10(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposalDescMaxLength: Dict[str, Any]


class UpdateConfigAction11(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposalInvoiceMaxLength: Dict[str, Any]


class UpdateConfigAction12(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposalTitleMaxLength: Dict[str, Any]


class UpdateConfigAction13(BaseModel):
    class Config:
        extra = Extra.forbid

    configProposeFeeMumav: Dict[str, Any]


class UpdateConfigAction14(BaseModel):
    class Config:
        extra = Extra.forbid

    configSuccessReward: Dict[str, Any]


class UpdateConfigParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    updateConfigNewValue: str
    updateConfigAction: (
        UpdateConfigAction
        | UpdateConfigAction1
        | UpdateConfigAction2
        | UpdateConfigAction3
        | UpdateConfigAction4
        | UpdateConfigAction5
        | UpdateConfigAction6
        | UpdateConfigAction7
        | UpdateConfigAction8
        | UpdateConfigAction9
        | UpdateConfigAction10
        | UpdateConfigAction11
        | UpdateConfigAction12
        | UpdateConfigAction13
        | UpdateConfigAction14
    )
