# generated by datamodel-codegen:
#   filename:  votingRoundVote.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Extra, Field


class Vote(BaseModel):
    class Config:
        extra = Extra.forbid

    nay: Dict[str, Any]


class Vote1(BaseModel):
    class Config:
        extra = Extra.forbid

    pass_: Dict[str, Any] = Field(..., alias='pass')


class Vote2(BaseModel):
    class Config:
        extra = Extra.forbid

    yay: Dict[str, Any]


class VotingRoundVoteParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    vote: Vote | Vote1 | Vote2
    empty: Dict[str, Any]
