# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    farmNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createFarmIsPaused: bool
    createFarmMTokenIsPaused: bool
    trackFarmIsPaused: bool
    untrackFarmIsPaused: bool


class FarmFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    trackedFarms: List[str]
    lambdaLedger: Dict[str, str]
    farmLambdaLedger: Dict[str, str]
    mFarmLambdaLedger: Dict[str, str]
