# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    farmNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createFarmIsPaused: bool
    createFarmMTokenIsPaused: bool
    trackFarmIsPaused: bool
    untrackFarmIsPaused: bool


class FarmFactoryStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    breakGlassConfig: BreakGlassConfig
    trackedFarms: List[str]
    lambdaLedger: Dict[str, str]
    farmLambdaLedger: Dict[str, str]
    mFarmLambdaLedger: Dict[str, str]
