# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    collateralRatio: str
    liquidationRatio: str
    liquidationFeePercent: str
    adminLiquidationFeePercent: str
    minimumLoanFeePercent: str
    minimumLoanFeeTreasuryShare: str
    interestTreasuryShare: str
    decimals: str
    interestRateDecimals: str
    maxDecimalsForCalculation: str
    lastCompletedDataMaxDelay: str
    maxVaultLiquidationPercent: str
    liquidationDelayInMins: str
    liquidationMaxDuration: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    addLiquidityIsPaused: bool
    borrowIsPaused: bool
    closeVaultIsPaused: bool
    liquidateVaultIsPaused: bool
    markForLiquidationIsPaused: bool
    registerDepositIsPaused: bool
    registerVaultCreationIsPaused: bool
    registerWithdrawalIsPaused: bool
    removeLiquidityIsPaused: bool
    repayIsPaused: bool
    setCollateralTokenIsPaused: bool
    setLoanTokenIsPaused: bool
    vaultDepositIsPaused: bool
    vaultDepositStakedTokenIsPaused: bool
    vaultOnLiquidateIsPaused: bool
    vaultWithdrawIsPaused: bool
    vaultWithdrawStakedTokenIsPaused: bool


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    collateralBalanceLedger: Dict[str, str]
    loanToken: str
    loanOutstandingTotal: str
    loanPrincipalTotal: str
    loanInterestTotal: str
    loanDecimals: str
    borrowIndex: str
    lastUpdatedBlockLevel: str
    lastUpdatedTimestamp: str
    markedForLiquidationLevel: str
    liquidationEndLevel: str


class Vault(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value


class TokenType(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenType1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenType2(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class CollateralTokenLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenContractAddress: str
    tokenDecimals: str
    oracleAddress: str
    protected: bool
    isScaledToken: bool
    isStakedToken: bool
    stakingContractAddress: str | None
    totalDeposited: str
    maxDepositAmount: str | None
    tokenType: TokenType | TokenType1 | TokenType2
    isPaused: bool


class TokenType3(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class TokenType4(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenType5(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class LoanTokenLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenType: TokenType3 | TokenType4 | TokenType5
    tokenDecimals: str
    oracleAddress: str
    rawMTokensTotalSupply: str
    mTokenAddress: str
    tokenPoolTotal: str
    totalBorrowed: str
    totalRemaining: str
    reserveRatio: str
    utilisationRate: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    minRepaymentAmount: str
    currentInterestRate: str
    lastUpdatedBlockLevel: str
    tokenRewardIndex: str
    borrowIndex: str
    isPaused: bool


class LendingControllerStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    breakGlassConfig: BreakGlassConfig
    mvnTokenAddress: str
    governanceAddress: str
    vaults: List[Vault]
    ownerLedger: Dict[str, List[str]]
    collateralTokenLedger: Dict[str, CollateralTokenLedger]
    loanTokenLedger: Dict[str, LoanTokenLedger]
    lambdaLedger: Dict[str, str]
