# generated by datamodel-codegen:
#   filename:  claim.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ClaimParameter(BaseModel):
    __root__: List[str]
