# generated by datamodel-codegen:
#   filename:  closeFarm.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CloseFarmParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
