# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class InitFarmParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalBlocks: str
    currentRewardPerBlock: str
    forceRewardFromTransfer: bool
    infinite: bool
