# generated by datamodel-codegen:
#   filename:  unpauseAll.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UnpauseAllParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
