# generated by datamodel-codegen:
#   filename:  createVault.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra


class DepositorsConfigItem(BaseModel):
    class Config:
        extra = Extra.forbid

    any: Dict[str, Any]


class DepositorsConfigItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelist: Dict[str, Any]


class Depositors(BaseModel):
    class Config:
        extra = Extra.forbid

    whitelistedDepositors: List[str]
    depositorsConfig: Union[DepositorsConfigItem, DepositorsConfigItem1]


class CreateVaultParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    delegate: Optional[str]
    loanTokenName: str
    depositors: Depositors
