# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    aggregatorNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    createAggregatorIsPaused: bool
    trackAggregatorIsPaused: bool
    untrackAggregatorIsPaused: bool
    distributeRewardMvrkIsPaused: bool
    distributeRewardStakedMvnIsPaused: bool


class AggregatorFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    trackedAggregators: List[str]
    breakGlassConfig: BreakGlassConfig
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    lambdaLedger: Dict[str, str]
    aggregatorLambdaLedger: Dict[str, str]
