# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aggregatorNameMaxLength: str
    empty: Dict[str, Any]


class BreakGlassConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    createAggregatorIsPaused: bool
    trackAggregatorIsPaused: bool
    untrackAggregatorIsPaused: bool
    distributeRewardMvrkIsPaused: bool
    distributeRewardStakedMvnIsPaused: bool


class AggregatorFactoryStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    trackedAggregators: List[str]
    breakGlassConfig: BreakGlassConfig
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    lambdaLedger: Dict[str, str]
    aggregatorLambdaLedger: Dict[str, str]
