# generated by DipDup 8.0.0

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    threshold: str
    actionExpiryDays: str
    councilMemberNameMaxLength: str
    councilMemberWebsiteMaxLength: str
    councilMemberImageMaxLength: str
    requestTokenNameMaxLength: str
    requestPurposeMaxLength: str


class CouncilMembers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    website: str
    image: str


class CouncilActionsLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    initiator: str
    actionType: str
    executed: bool
    status: str
    signersCount: str
    dataMap: Dict[str, str]
    startDateTime: str
    startLevel: str
    executedDateTime: str | None = None
    executedLevel: str | None = None
    expirationDateTime: str


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    address: str


class CouncilActionsSigner(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Dict[str, Any]


class CouncilStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin: str
    metadata: Dict[str, str]
    config: Config
    mvnTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, Dict[str, Any]]
    generalContracts: Dict[str, str]
    councilMembers: Dict[str, CouncilMembers]
    councilSize: str
    councilActionsLedger: Dict[str, CouncilActionsLedger]
    councilActionsSigners: List[CouncilActionsSigner]
    actionCounter: str
    lambdaLedger: Dict[str, str]
