# generated by datamodel-codegen:
#   filename:  transfer.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra


class Token(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class Token1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class Token2(BaseModel):
    class Config:
        extra = Extra.forbid

    mav: Dict[str, Any]


class TransferParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    to_: str
    amount: str
    token: Token | Token1 | Token2


class TransferParameter(BaseModel):
    __root__: List[TransferParameterItem]
