# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra


class Config(BaseModel):
    class Config:
        extra = Extra.forbid

    collateralRatio: str
    liquidationRatio: str
    liquidationFeePercent: str
    adminLiquidationFeePercent: str
    minimumLoanFeePercent: str
    minimumLoanFeeTreasuryShare: str
    interestTreasuryShare: str
    decimals: str
    interestRateDecimals: str
    maxDecimalsForCalculation: str
    maxVaultLiquidationPercent: str
    liquidationDelayInMins: str
    liquidationMaxDuration: str


class BreakGlassConfig(BaseModel):
    class Config:
        extra = Extra.forbid

    addLiquidityIsPaused: bool
    borrowIsPaused: bool
    closeVaultIsPaused: bool
    liquidateVaultIsPaused: bool
    markForLiquidationIsPaused: bool
    registerDepositIsPaused: bool
    registerVaultCreationIsPaused: bool
    registerWithdrawalIsPaused: bool
    removeLiquidityIsPaused: bool
    repayIsPaused: bool
    setCollateralTokenIsPaused: bool
    setLoanTokenIsPaused: bool
    vaultDepositIsPaused: bool
    vaultDepositStakedTokenIsPaused: bool
    vaultOnLiquidateIsPaused: bool
    vaultWithdrawIsPaused: bool
    vaultWithdrawStakedTokenIsPaused: bool


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    collateralBalanceLedger: Dict[str, str]
    loanToken: str
    loanOutstandingTotal: str
    loanPrincipalTotal: str
    loanInterestTotal: str
    loanDecimals: str
    borrowIndex: str
    lastUpdatedBlockLevel: str
    lastUpdatedTimestamp: str
    markedForLiquidationLevel: str
    liquidationEndLevel: str


class Vault(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value


class TokenTypeItem(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa2(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenTypeItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa2


class TokenTypeItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class CollateralTokenLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenContractAddress: str
    tokenDecimals: str
    oracleAddress: str
    protected: bool
    isScaledToken: bool
    isStakedToken: bool
    stakingContractAddress: Optional[str]
    totalDeposited: str
    maxDepositAmount: Optional[str]
    tokenType: Union[TokenTypeItem, TokenTypeItem1, TokenTypeItem2]
    isPaused: bool


class TokenTypeItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    fa12: str


class Fa21(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenContractAddress: str
    tokenId: str


class TokenTypeItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: Fa21


class TokenTypeItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    tez: Dict[str, Any]


class LoanTokenLedger(BaseModel):
    class Config:
        extra = Extra.forbid

    tokenName: str
    tokenType: Union[TokenTypeItem3, TokenTypeItem4, TokenTypeItem5]
    tokenDecimals: str
    oracleAddress: str
    lpTokensTotal: str
    lpTokenContractAddress: str
    lpTokenId: str
    tokenPoolTotal: str
    totalBorrowed: str
    totalRemaining: str
    reserveRatio: str
    utilisationRate: str
    optimalUtilisationRate: str
    baseInterestRate: str
    maxInterestRate: str
    interestRateBelowOptimalUtilisation: str
    interestRateAboveOptimalUtilisation: str
    minRepaymentAmount: str
    currentInterestRate: str
    lastUpdatedBlockLevel: str
    accumulatedRewardsPerShare: str
    borrowIndex: str
    isPaused: bool


class LendingControllerStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    metadata: Dict[str, str]
    config: Config
    breakGlassConfig: BreakGlassConfig
    mvkTokenAddress: str
    governanceAddress: str
    whitelistContracts: Dict[str, str]
    generalContracts: Dict[str, str]
    whitelistTokenContracts: Dict[str, str]
    vaults: List[Vault]
    ownerLedger: Dict[str, List[str]]
    collateralTokenLedger: Dict[str, CollateralTokenLedger]
    loanTokenLedger: Dict[str, LoanTokenLedger]
    lambdaLedger: Dict[str, str]
    tempMap: Dict[str, str]
