# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class SnapshotLedgerKey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    address: str
