# generated by datamodel-codegen:
#   filename:  snapshotLedger_key.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SnapshotLedgerKey(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str
