# generated by DipDup 8.0.0

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class SnapshotLedgerValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    totalStakedMvnBalance: str
    totalDelegatedAmount: str
    totalVotingPower: str
    accumulatedRewardsPerShare: str
    ready: bool
    nextSnapshotCycleId: str | None = None
